# deployments/kubernetes/overlays/development/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
namePrefix: dev-
namespace: portfolio
patchesStrategicMerge:
  - patch-deployment.yaml