apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
namePrefix: dev-
namespace: portfolio
patches:
  - path: patch-deployment.yaml
    target:
      kind: Deployment
      name: portfolio