# deployments/kubernetes/overlays/production/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/configmap.yaml
  - ../../base/deployment.yaml
  - ../../base/service.yaml
  - ../../base/ingress.yaml