version: '3.8'

services:
  portfolio:
    image: ardidafa/portfolio:latest
    container_name: portfolio
    restart: unless-stopped
    ports:
      - "3002:80"  # Menghindari konflik dengan Nginx di host yang menggunakan port 80
    networks:
      - web
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:80"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    environment:
      - NODE_ENV=production

networks:
  web:
    driver: bridge