# Periksa VirtualService
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: portfolio
  namespace: portfolio
spec:
  hosts:
    - "portfolio.glanze.site"
  gateways:
    - portfolio-gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: portfolio.portfolio.svc.cluster.local  # FQDN service
            port:
              number: 80