apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: portfolio
  namespace: portfolio
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`portfolio.glanze.site`)
      kind: Rule
      services:
        - name: portfolio
          port: 80
      middlewares:
        - name: redirect-https
  tls:
    certResolver: letsencrypt
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: redirect-https
  namespace: portfolio
spec:
  redirectScheme:
    scheme: https
    permanent: true