apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: portfolio

commonLabels:
  environment: development
  app.kubernetes.io/managed-by: kustomize

patchesStrategicMerge:
  - patch-deployment.yaml

replicas:
  - name: portfolio
    count: 1