apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio
spec:
  template:
    metadata:
      annotations:
        environment: "development"
    spec:
      containers:
        - name: portfolio
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          env:
            - name: NODE_ENV
              value: "development"
            - name: DEBUG
              value: "true"