apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: portfolio-tls-cert
  namespace: istio-system
spec:
  secretName: portfolio-tls-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: portfolio.glanze.site
  dnsNames:
    - portfolio.glanze.site