apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: portfolio
  namespace: portfolio
  annotations:
    cert-manager.io/issuer: "letsencrypt-traefik"
spec:
  ingressClassName: traefik
  rules:
    - host: portfolio.glanze.site
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: portfolio
                port:
                  number: 80
  tls:
    - hosts:
        - portfolio.glanze.site
      secretName: portfolio-tls  # Nama secret TLS