apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-traefik
  namespace: portfolio
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: ardidafa21@gmail.com
    privateKeySecretRef:
      name: letsencrypt-traefik-key
    solvers:
      - http01:
          ingress:
            class: traefik