apiVersion: v1
kind: Service
metadata:
  name: portfolio
  namespace: portfolio  # Ganti dari istio-system ke portfolio
  labels:
    app: portfolio
spec:
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: portfolio